[general]
import = [
  "/Users/jv/.dots/alacritty/themes/solarized-dark.toml",
  "/Users/jv/.dots/alacritty/keybindings.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = false
startup_mode = "SimpleFullscreen"
title = "Alacritty"
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "ButtonLess"
