[keyboard]
bindings = [
{ key = "A", mods = "Alt", chars = "\u001Ba" },
{ key = "A", mods = "Alt|Shift", chars = "\u001BA" },
{ key = "B", mods = "Alt", chars = "\u001Bb" },
{ key = "B", mods = "Alt|Shift", chars = "\u001BB" },
{ key = "C", mods = "Alt", chars = "\u001Bc" },
{ key = "C", mods = "Alt|Shift", chars = "\u001BC" },
{ key = "D", mods = "Alt", chars = "\u001Bd" },
{ key = "D", mods = "Alt|Shift", chars = "\u001BD" },
{ key = "E", mods = "Alt", chars = "\u001Be" },
{ key = "E", mods = "Alt|Shift", chars = "\u001BE" },
{ key = "F", mods = "Alt", chars = "\u001Bf" },
{ key = "F", mods = "Alt|Shift", chars = "\u001BF" },
{ key = "G", mods = "Alt", chars = "\u001Bg" },
{ key = "G", mods = "Alt|Shift", chars = "\u001BG" },
{ key = "H", mods = "Alt", chars = "\u001Bh" },
{ key = "H", mods = "Alt|Shift", chars = "\u001BH" },
{ key = "I", mods = "Alt", chars = "\u001Bi" },
{ key = "I", mods = "Alt|Shift", chars = "\u001BI" },
{ key = "J", mods = "Alt", chars = "\u001Bj" },
{ key = "J", mods = "Alt|Shift", chars = "\u001BJ" },
{ key = "K", mods = "Alt", chars = "\u001Bk" },
{ key = "K", mods = "Alt|Shift", chars = "\u001BK" },
{ key = "L", mods = "Alt", chars = "\u001Bl" },
{ key = "L", mods = "Alt|Shift", chars = "\u001BL" },
{ key = "M", mods = "Alt", chars = "\u001Bm" },
{ key = "M", mods = "Alt|Shift", chars = "\u001BM" },
{ key = "N", mods = "Alt", chars = "\u001Bn" },
{ key = "N", mods = "Alt|Shift", chars = "\u001BN" },
{ key = "O", mods = "Alt", chars = "\u001Bo" },
{ key = "O", mods = "Alt|Shift", chars = "\u001BO" },
{ key = "P", mods = "Alt", chars = "\u001Bp" },
{ key = "P", mods = "Alt|Shift", chars = "\u001BP" },
{ key = "Q", mods = "Alt", chars = "\u001Bq" },
{ key = "Q", mods = "Alt|Shift", chars = "\u001BQ" },
{ key = "R", mods = "Alt", chars = "\u001Br" },
{ key = "R", mods = "Alt|Shift", chars = "\u001BR" },
{ key = "S", mods = "Alt", chars = "\u001Bs" },
{ key = "S", mods = "Alt|Shift", chars = "\u001BS" },
{ key = "T", mods = "Alt", chars = "\u001Bt" },
{ key = "T", mods = "Alt|Shift", chars = "\u001BT" },
{ key = "U", mods = "Alt", chars = "\u001Bu" },
{ key = "U", mods = "Alt|Shift", chars = "\u001BU" },
{ key = "V", mods = "Alt", chars = "\u001Bv" },
{ key = "V", mods = "Alt|Shift", chars = "\u001BV" },
{ key = "W", mods = "Alt", chars = "\u001Bw" },
{ key = "W", mods = "Alt|Shift", chars = "\u001BW" },
{ key = "X", mods = "Alt", chars = "\u001Bx" },
{ key = "X", mods = "Alt|Shift", chars = "\u001BX" },
{ key = "Y", mods = "Alt", chars = "\u001By" },
{ key = "Y", mods = "Alt|Shift", chars = "\u001BY" },
{ key = "Z", mods = "Alt", chars = "\u001Bz" },
{ key = "Z", mods = "Alt|Shift", chars = "\u001BZ" },
{ key = "Key0", mods = "Alt", chars = "\u001B0" },
{ key = "Key1", mods = "Alt", chars = "\u001B1" },
{ key = "Key2", mods = "Alt", chars = "\u001B2" },
{ key = "Key3", mods = "Alt", chars = "\u001B3" },
{ key = "Key3", mods = "Alt|Shift", chars = "\u001B#" },
{ key = "Key4", mods = "Alt", chars = "\u001B4" },
{ key = "Key5", mods = "Alt", chars = "\u001B5" },
{ key = "Key5", mods = "Alt|Shift", chars = "\u001B%" },
{ key = "Key6", mods = "Alt", chars = "\u001B6" },
{ key = "Key6", mods = "Alt|Shift", chars = "\u001B^" },
{ key = "Key7", mods = "Alt", chars = "\u001B7" },
{ key = "Key8", mods = "Alt", chars = "\u001B8" },
{ key = "Key8", mods = "Alt|Shift", chars = "\u001B*" },
{ key = "Key9", mods = "Alt", chars = "\u001B9" },
{ key = "`", mods = "Alt", chars = "\u001B`" },
{ key = "`", mods = "Alt|Shift", chars = "\u001B~" },
{ key = "Comma", mods = "Alt|Shift", chars = "\u001B<" },
{ key = "Minus", mods = "Alt|Shift", chars = "\u001B_" },
{ key = "Slash", mods = "Alt", chars = "\u001B/" },
{ key = "Backslash", mods = "Alt", chars = "\u001B\\" },
{ key = "Backslash", mods = "Alt|Shift", chars = "\u001B|" },
{ key = "Period", mods = "Alt", chars = "\u001B." },
{ key = "Period", mods = "Alt|Shift", chars = "\u001B>" },
{ key = "Space", mods = "Control", chars = "\u0000" },
]
