#!/usr/bin/env bash

if [[ ${BASH_VERSINFO[0]} -lt 4 ]]; then exit; fi

COMMIT_MSG_FILE=$1
#COMMIT_SOURCE=$2
#SHA1=$3

# This adds the Work item issue identification as a trailer to the commit message automatically (generic on tool, works with Jira, Github, Linear, etc)
# For github need to somehow identify it and change the id to #id if that is not in the branch name
BRANCH=$(git branch --no-color --show-current)

ISSUE=$(echo "$BRANCH" | sed -rn "s#([[:lower:]]+/)?([[:alpha:]]+-[[:digit:]]+)[/-].*#\2#p")
if [[ -n "$ISSUE" ]]; then
  #git interpret-trailers --in-place --where before --no-divider --trailer "Work-item-action: close|fix|resolve $ISSUE" "$COMMIT_MSG_FILE"
  git interpret-trailers --in-place --where before --no-divider --trailer "Work-item-id: ${ISSUE^^}" "$COMMIT_MSG_FILE"
fi
