#!/bin/bash

COMMIT_MSG_FILE=$1
#COMMIT_SOURCE=$2
#SHA1=$3

# This adds the Jira issue identification as a trailer to the commit message automatically
BRANCH=$(git branch --no-color --show-current)

ISSUE_WITH_SLASH=$(echo "$BRANCH" | cut -f1 -d/ -s)
ISSUE_WITH_DASH=$(echo "$BRANCH" | cut -f1,2 -d- -s)

ISSUE=${ISSUE_WITH_SLASH:-$ISSUE_WITH_DASH}
if [[ "$ISSUE" =~ [[:upper:]]+-[[:digit:]]+.* ]]; then
  #git interpret-trailers --in-place --where before --no-divider --trailer "Jira-issue-action: close|fix|resolve $ISSUE" "$COMMIT_MSG_FILE"
  git interpret-trailers --in-place --where before --no-divider --trailer "Jira-issue: $ISSUE" "$COMMIT_MSG_FILE"
fi
