# Add versions
tap 'homebrew/versions'

# Install cask with versions and fonts
tap 'caskroom/cask'
brew 'caskroom/cask/brew-cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'

# Tap private repos
tap 'juanibiapina/zas'

# Install Apps
cask '1password3'
cask 'adium'
cask 'airmail-beta'
cask 'alfred'
cask 'appcleaner'
cask 'dash'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'google-hangouts'
cask 'iterm2'
cask 'java'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'virtualbox'
cask 'vlc'
cask 'karabiner'
cask 'messenger'
cask 'chitchat'

# Install fonts
cask 'font-inconsolata-for-powerline'
cask 'font-sauce-code-powerline'

# Install command line tools
brew 'ack'
brew 'bats'
brew 'ctags'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'elasticsearch'
brew 'fish'
brew 'git'
brew 'ghi'
brew 'hub'
brew 'imagemagick'
brew 'mongodb'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'zas'
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'tmux'
brew 'reattach-to-user-namespace'

# Install neovim
tap 'neovim/neovim'
brew 'neovim', args: ['HEAD']
