# set up the terminal format
export PS1='\[\033[;32m\]\u@\h\[\033[1;33m\] \w \[\033[;31m\]$(__git_ps1 "(%s)")\$\[\033[00m\] '
# set the terminal colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagacad
# set the default editor
export EDITOR=vim

#source the configuration of the path
source "$HOME/.dots/bash/conf/path"

#source the configuration of the aliases
source "$HOME/.dots/bash/conf/aliases"

# this loads RVM into a shell session.
# needs RVM installed
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  
# set the bash-completion path
# needs bash-completion installed
if [ -f `brew --prefix`/etc/bash_completion ]; then
	. `brew --prefix`/etc/bash_completion
fi
