#source the configuration of the path
source "$HOME/.dots/bash/conf/path"

#source the configuration of the aliases
source "$HOME/.dots/bash/conf/aliases"

#source the configuration of the functions
source "$HOME/.dots/bash/conf/functions"

#source general configuration
source "$HOME/.dots/bash/conf/general"

#source rvm configuration
source "$HOME/.dots/bash/conf/rvm"

#source bash_completion configuration
source "$HOME/.dots/bash/conf/bash_completion"

#source bash_profile.local if it exists
if [ -e "$HOME/.bash_profile.local" ]; then
  source "$HOME/.bash_profile.local"
fi
