#source the configuration of the path
source "$HOME/.dots/bash/conf/path"

#source the configuration of the aliases
source "$HOME/.dots/bash/conf/aliases"

#source general configuration
source "$HOME/.dots/bash/conf/general"

#source rvm configuration
source "$HOME/.dots/bash/conf/rvm"

#source bash_completion configuration
source "$HOME/.dots/bash/conf/bash_completion"
